italic = { "i" }
shadowed = { "s" }
wide = { "w" }
narrow = { "n" }
normal = { "m" }
default_color = { "g" }
bold = { "o" }
reset = { "z" }
capitals = { "t" }
color = { (!"$" ~ ANY){3} }

tag = {
    "$$" |
    ("$" ~ (italic | shadowed | wide | narrow | normal |
            default_color | bold | reset | capitals | color)) |
    ("$" ~ HEX_DIGIT ~ (!"$" ~ ANY){2}) |
    ("$" ~ ANY)
}

char = { !"$" ~ ANY }
text = @{ char+ }

name = { (tag | text)* }
